import Head from "next/head";
import Sidebar from "@components/Sidebar";
import Feed from "@components/Feed";

export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="mx-auto flex min-h-screen max-w-[1500px] bg-black">
        <Sidebar />
        <Feed />
        {/* Widget */}

        {/* Modal */}
      </main>
    </>
  );
}
